name: anchorsteering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - accelerate>=1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.7.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - automated-interpretability==0.0.6
      - babe==0.0.7
      - beartype==0.14.1
      - beautifulsoup4==4.12.3
      - better-abc==0.0.3
      - blobfile==2.1.1
      - boostedblob==0.15.5
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - config2py==0.1.36
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets>=2.14.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dol==0.2.95
      - einops==0.8.0
      - fancy-einsum==0.0.3
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gprof2dot==2024.6.6
      - graze==0.1.27
      - gymnasium==0.29.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx>=0.24.0
      - huggingface-hub==0.27.0
      - i2==0.1.45
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - jaxtyping==0.2.36
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lxml==4.9.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib>=3.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy>=1.24.0
      - opencv-python==4.10.0.84
      - orjson==3.10.13
      - pandas>=2.0.0
      - patsy==1.0.1
      - pillow==11.0.0
      - plotly>=5.14.0
      - plotly-express==0.4.1
      - pluggy==1.5.0
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.0
      - py2store==0.1.20
      - pyarrow==18.1.0
      - pycryptodomex==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pytest==8.3.4
      - pytest-profiling==1.8.1
      - python-dotenv>=1.0.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.0.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rtree==1.3.0
      - ruckig==0.14.0
      - sae-lens==5.3.0
      - safetensors==0.4.5
      - sapien==2.2.2
      - scikit-learn>=1.3.0
      - scipy>=1.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - simple-parsing==0.1.6
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - statsmodels>=0.14.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch>=2.0.0
      - tqdm>=4.65.0
      - transformer-lens==2.11.0
      - transformers>=4.35.0
      - transforms3d==0.4.2
      - trimesh==4.5.2
      - typeguard==4.4.1
      - typer==0.12.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvloop==0.21.0
      - wandb==0.19.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zstandard==0.22.0
      - openai>=1.0.0
      - anthropic==0.49.0
      - nnsight==0.4.5
      - bitsandbytes==0.45.4
      - seaborn>=0.12.0
      - mdmm==0.1.3
      - sentence-transformers>=2.2.0
      - xgboost>=1.7.0
      - pkld>=1.0.0
